In [ ]:
# Introduction to NumPy Arrays

# NumPy is a powerful library for numerical computing in Python.
# It provides support for multidimensional arrays and a wide range of mathematical functions to operate on these arrays efficiently.

# Example 1: Importing NumPy
# Before using NumPy, we need to import it.
import numpy as np

# Example 2: Creating NumPy Arrays
# NumPy arrays can be created from Python lists or using built-in functions.
# Here's an example of creating a 1D NumPy array from a list.
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print("1D Array:", my_array)

# Example 3: Multidimensional Arrays
# NumPy arrays can have multiple dimensions.
# Here's an example of creating a 2D NumPy array from a list of lists.
my_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:")
print(my_matrix)

1D Array: [1 2 3 4 5]
2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Example 1: Creating an array from 0 to 9 with step 1
arr1 = np.arange(10)
print("Example 1:", arr1)

# Example 2: Creating an array from 1 to 10 with step 2
arr2 = np.arange(1, 11, 2)
print("Example 2:", arr2)

# Example 3: Creating an array of 5 evenly spaced numbers from 0 to 10
arr3 = np.linspace(0, 10, 5)
print("Example 3:", arr3)

# Creating an array of zeros
zeros_array = np.zeros(5)
print("Array of zeros:")
print(zeros_array)

# Creating an array of ones
ones_array = np.ones(5)
print("\nArray of ones:")
print(ones_array)

# Reshaping arrays
arr = np.arange(12)  # Creating a 1D array with 12 elements
reshaped_arr = np.reshape(arr, (3, 4))  # Reshaping to a 3x4 array
print("\nOriginal array:")
print(arr)
print("\nReshaped array:")
print(reshaped_arr)

# Generating random integers
print("\nGenerating random integers:")
rand_integers = np.random.randint(1, 10, size=(3, 3))  # Generating a 3x3 array of random integers between 1 and 10
print(rand_integers)

# Generating random numbers from a normal distribution
print("\nGenerating random numbers from a normal distribution:")
rand_normal = np.random.normal(0, 1, size=(3, 3))  # Generating a 3x3 array of random numbers from a normal distribution with mean 0 and standard deviation 1
print(rand_normal)

Example 1: [0 1 2 3 4 5 6 7 8 9]
Example 2: [1 3 5 7 9]
Example 3: [ 0.   2.5  5.   7.5 10. ]
Array of zeros:
[0. 0. 0. 0. 0.]

Array of ones:
[1. 1. 1. 1. 1.]

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Generating random integers:
[[9 1 6]
 [7 6 6]
 [3 3 5]]

Generating random numbers from a normal distribution:
[[ 1.02806255  2.02715453  1.1355819 ]
 [-0.64565629  0.16779693 -0.60319703]
 [-1.20829628 -0.61911051  0.11405014]]


In [ ]:
my_array = np.ones((5,5))
# Here's how to access these attributes.
print("Shape of array:", my_array.shape)
print("Size of array:", my_array.size)
print("Data type of array:", my_array.dtype)
print(my_array)

Shape of array: (5, 5)
Size of array: 25
Data type of array: float64
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
print(matrix1)
print(matrix2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
# NumPy Array Attributes and Operations
# NumPy arrays have various attributes and functions to perform operations on arrays efficiently.

# Example 4: Array Attributes
# NumPy arrays have attributes like shape, size, and dtype.
# Here's how to access these attributes.
print("Shape of array:", my_array.shape)
print("Size of array:", my_array.size)
print("Data type of array:", my_array.dtype)

# Example 5: Array Operations
# NumPy arrays support element-wise operations and broadcasting.
# Here's an example of performing arithmetic operations on arrays.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("Element-wise Addition:", arr1 + arr2)
print("Element-wise Subtraction:", arr1 - arr2)
print("Element-wise Multiplication:", arr1 * arr2)

# Example 6: Broadcasting
# NumPy allows arrays with different shapes to be broadcasted to perform arithmetic operations efficiently.
# Here's an example of broadcasting with a scalar value.
scalar = 2
print("Broadcasted Addition with Scalar:", arr1 + scalar)

# Example 7: Matrix Multiplication
# We can perform matrix multiplication using the dot() function.
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
print(matrix1)
print(matrix2)
print("Matrix multiplication:\n", np.dot(matrix1, matrix2))


Shape of array: (5,)
Size of array: 5
Data type of array: int64
Element-wise Addition: [5 7 9]
Element-wise Subtraction: [-3 -3 -3]
Element-wise Multiplication: [ 4 10 18]
Broadcasted Addition with Scalar: [3 4 5]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Matrix multiplication:
 [[19 22]
 [43 50]]


In [ ]:
my_array = np.arange(1,6)
my_matrix = np.random.normal(0, 1, size=(3, 3))

print(my_array)
print(my_matrix)

[1 2 3 4 5]
[[-0.93658305  1.40500449  2.62367059]
 [-0.94020122 -0.66503775 -0.60749297]
 [ 0.10038823 -1.14781697  1.89741106]]


In [ ]:
print(my_matrix[0,2])

2.623670594116359


In [ ]:
# NumPy Array Indexing and Slicing

# NumPy arrays support advanced indexing and slicing operations to access and manipulate array elements efficiently.

# Example 8: Array Indexing
# Indexing in NumPy arrays is similar to indexing in Python lists.
# Here's an example of accessing individual elements and rows/columns of a 2D array.
print("First element of array:", my_array[0])
print("Element at row 1, column 2:", my_matrix[0, 1])

# Example 9: Array Slicing
# Slicing allows us to extract a subarray from a larger array.
# Here's an example of slicing a 1D array and a 2D array.
print("Sliced array:", my_array[1:4])
print("Sliced submatrix:")
print(my_matrix[:2, 1:])


First element of array: 1
Element at row 1, column 2: 2
Sliced array: [2 3 4]
Sliced submatrix:
[[2 3]
 [5 6]]


In [ ]:
# Example 8=10: Universal Functions (ufuncs)
# NumPy provides a collection of mathematical functions called universal functions (ufuncs) that operate element-wise on arrays.
arr = np.array([1, 2, 3, 4, 5])
print("Square root of elements:", np.sqrt(arr))  # Output: [1.         1.41421356 1.73205081 2.         2.23606798]

Square root of elements: [1.         1.41421356 1.73205081 2.         2.23606798]
